const handleError = (req, res, next) => {
    try {
        
    } catch (error) {
        console.log(error)
    }
}

module.exports = handleError